### ISSUE TITLE
Add new magicites (4*) to tracking drop list

### ISSUE THREAD

**Issue by genoism** [ThauEx/ffrk-proxy#107]
Hello, any chance the drop tracker could get updated with the new list of 4* magicites?

Thank you!

According to enlir's spreadsheet here's the info I suspect you would need (name and ID))

Firemane | 161000057
King Bomb | 161000058
Maliris | 161000059
Krysta | 161000060
Dullahan | 161000061
Isgebind | 161000062
Mimic Queen | 161000069
Garuda | 161000070
Ixion | 161000071
Earth Guardian | 161000066
Catastrophe | 161000067
Midgardsormr | 161000068
Sylph | 161000063
Silver Dragon | 161000064
Tiamat | 161000065
Gizamaluke | 161000072
Octomammoth | 161000073
Kraken | 161000074
Seraph | 161000075
Evrae | 161000076
Siren | 161000077
Dragon Zombie | 161000078
Necrophobe | 161000079
Hades | 161000080

**Comment by c10u6** [comment]
For anyone else like me who wanted the same thing, go into /lib/properties/items.json and edit it to add in the following:

  "161000057": "Firemane 4*",
  "161000058": "King Bomb 4*",
  "161000059": "Maliris 4*",
  "161000060": "Krysta 4*",
  "161000061": "Dullahan 4*",
  "161000062": "Isgebind 4*",
  "161000063": "Sylph 4*",
  "161000064": "Silver Dragon 4*",
  "161000065": "Tiamat 4*",
  "161000066": "Earth Guardian 4*",
  "161000067": "Catastrophe 4*",
  "161000068": "Midgardsormr 4*",
  "161000069": "Mimic Queen 4*",
  "161000070": "Garuda 4*",
  "161000071": "Ixion 4*",
  "161000072": "Gizamaluke 4*",
  "161000073": "Octomammoth 4*",
  "161000074": "Kraken 4*",
  "161000075": "Seraph 4*",
  "161000076": "Evrae 4*",
  "161000077": "Siren 4*",
  "161000078": "Dragon Zombie 4*",
  "161000079": "Necrophone 4*",
  "161000080": "Hades 4*",

The 4* is because it shows up as 3* in the window still. The OP's list had wind and lightning magicites switched. Not sure about the rest but my order should be right. Good luck farming!

**Comment by ThauEx** [comment]
I added these in the new pre release, so I will close this for now.
