### ISSUE TITLE
Proxy server authentification

### ISSUE THREAD

**Issue by JacomoFuchs** [ThauEx/ffrk-proxy#36]
Hey,

thanks for making such a great proxy script! I would like to open my firewall so i can access the proxy from outside my wifi, but I don't want to open it for everybody because normal surfing works as well...

Is there a way to add autentification to access the proxy server?

I can do pretty much everything with tutorials, I'm just not a programmer/coder...

**Comment by ThauEx** [comment]
This should be possible, I will see what I can do.

**Comment by SirPhoenix88** [comment]
I want this too!

**Comment by ThauEx** [comment]
Since the latest release is out, I will focus on this now!

**Comment by ThauEx** [comment]
I made some progress. Basic auth support is working, but only tested in browser for now. Now I have to build a nice way to configure it.

**Comment by ThauEx** [comment]
I pushed a test branch a few days ago, now I have the issue, that android is not supporting proxy auth... So I don't know, if this will work for most users without additional software.

**Comment by JacomoFuchs** [comment]
Does that mean you won't add this feature or will we be able to enable/disable it?

**Comment by ThauEx** [comment]
Well, hard to say. I made an initial implementation here: https://github.com/ThauEx/ffrk-proxy/tree/feature/proxy-auth
But I don't know, if the is worth it, because it would be more complicated to configure and I cannot say if the auth is working via https (not even chrome on desktop is supporting it). This would mean, that http requests do require a username and password and https requests are without it.
