### ISSUE TITLE
Ailments status in 600 range

### ISSUE THREAD

**Issue by jdel** [ThauEx/ffrk-proxy#64]
What can we do with them ? Is it possible to add the effect to Full Break to a regular attack ? 
If so how ? I have already tried to add 'CUSTOM_ATK_MATK_DEF_MDEF' to attach attributes, element type or even status to no avail.

**Comment by ThauEx** [comment]
What did you try to set? This one: `buddy.attack.elementType`?
Afaik only elements are supported and only one. Thats why we can't have a multi elemetal attack.

**Comment by jdel** [comment]
Yes that's what I tried, I tried all of them (buddy.attack.attributes, elementType and also buddy.status) so I don't open a ticket for nothing. 

I am not sure if it's doabe, I was just intrigued by the fact that 6xx status are present in the ailments.json but never used.

**Comment by KHShadowrunner** [comment]
I -think- I tried to add them at some point, but it wasn't behaving correctly. It's probably because the 600 statuses are tied to a type of attack, and would require some other adjustments to the basic attack block. I'm not sure tbh - but that's likely the cause as to why it's not working.

It's easier to confirm this if we have access to a regular dump of a 600-based attack/buff so that we can see what the actual attack is set up as (which is how I added elemental attacks in the first place).
