### ISSUE TITLE
Rasbian installation

### ISSUE THREAD

**Issue by Percolateur2000** [ThauEx/ffrk-proxy#66]
Hi !

Do you think you can make a ffrkproxy_install.sh ? Or anything noobproof ? i can help testing if you need !

I can't get it to work on raspberry pi 3 (to be honest i can't even install nodejs).

Cheers !

**Comment by jdel** [comment]
You need to be able to install NodeJS first, maybe this can help:

http://weworkweplay.com/play/raspberry-pi-nodejs/

**Comment by ThauEx** [comment]
Have you tried:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install -y nodejs
```

**Comment by Percolateur2000** [comment]
right now using node -v return `v0.10.29` so i might be good, testing furthermore

**Comment by ThauEx** [comment]
Thats too old, you need at least 12.x

**Comment by Percolateur2000** [comment]
i did update with
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install -y nodejs`

and `node -v
v6.5.0`

still not 12.x though

**Comment by jdel** [comment]
ThauEx meant 0.12.x. 6.x should be just fine.

**Comment by ThauEx** [comment]
12.x was a type, 6.5 is the latest and fine :)

**Comment by Percolateur2000** [comment]
oh my bad !

I did try `npm install` and it worked, but i hadn't downloaded your source code !

work much better with it !

Now i just have to update settings and i think i'm good to go !

will tell you once i'm done ! Thank you very much for your help !

**Comment by Percolateur2000** [comment]
update : works flawlessly with wifi and 4g ! 

Thank you very much !!

small last question : do you think i can get it to launch on startup ? Thank you !

**Comment by jdel** [comment]
Check out the link I sent 

5. Make it run on boot

This is the hardest part if you don't really know what you're doing.

You can define things to run on boot in /etc/rc.local. In that shell script, you don't have the same path as when you log in, so just running node app.js won't do the trick.

I tried a lot of different things that all gave errors like Illegal instruction or Permission denied or File not found.

What does work, is running one command as the default pi user. Because that user does have node in his path, the command is known.

su pi -c 'node /home/pi/server.js < /dev/null &'
I suggest using an absolute path to your Node.js-file just to make sure.

**Comment by Percolateur2000** [comment]
I won't move my files, actually in /home/pi/Downloads/ffrk-proxy-0.9.0

so i just have to `su pi -c 'node /home/pi/Downloads/ffrk-proxy-0.9.0/server.js < /dev/null &'` right ?

but i don't have a server.js i this folder (or is it the file you're talking about ?)

**Comment by jdel** [comment]
Maybe `su pi -c 'node /home/pi/Downloads/ffrk-proxy-0.9.0/bin/app.js < /dev/null &'`

**Comment by Percolateur2000** [comment]
besides folders, i have :
LICENCE
package.json
README.md
start.bat

**Comment by Percolateur2000** [comment]
Update : didn't get it to work, but nevermind i'll launch it whenever i need !

can we close this issue since it's working ? thank you !
