### ISSUE TITLE
FFRK 3.5.7 (JP) connection Error using 0.9.0 

### ISSUE THREAD

**Issue by Shoukon** [ThauEx/ffrk-proxy#71]
FFRK 3.5.7 (JP) connection Error using 0.9.0 

>ERR (socket request): Error: write after end
<ERR (proxy socket): Errir: This socket has been ended by the other party
>ERR (socket request): Error: write after end
Generating new TLS certificate for: dff.sp.mbga.jp

**Comment by ThauEx** [comment]
Well, these errors are normal. Is the proxy working fine? Or is it not connecting? Afaik the newest jp apk is not working, because of the new encryption stuff.

**Comment by Shoukon** [comment]
Downgrade to 3.5.6(JP), proxy working fine.

**Comment by ragingchaos** [comment]
I don't know why my Issue got closed, its practically the same as this guy's.

I not only get the above error message I also get a wall of text below. This WAS working when I was using 0.8.0 back in November. Using the same phone and only having changed to 0.9.0 back in Jan, neither works. 127.0.0.1 is set correctly as the bypass and once again this WAS working under old version.

0.9.0:
Proxying: GET http://127.0.0.1:26284/cache?fail_on_download_error=1&ver=t8vL3afaf32a204958e26ef7a719331b1ae2&url=static/ww/compile/en/js/app.js
{ [Error: connect ECONNREFUSED 127.0.0.1:26284]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 26284 } [ 'Error: connect ECONNREFUSED 127.0.0.1:26284',
  '    at Object.exports._errnoException (util.js:870:11)',
  '    at exports._exceptionWithHostPort (util.js:893:20)',
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)' ]
Proxying: GET http://ffrk.denagames.com/favicon.ico

0.8.0
ERR (socket request): Error: write after end
 <ERR (proxy socket): Error: This socket has been ended by the other party

**Comment by ThauEx** [comment]
In version 0.9.0 nothing changed regarding proxy logic.
I am using version 0.9.0 for months now and everything is working as expected.
For some reason it tries to access 127.0.0.1 and this is something the proxy cannot handle.

**Comment by jdel** [comment]
@ragingchaos, if you use proxydroid, you need to disable the whitelist.

**Comment by Shoukon** [comment]
Only ios version FFRK 3.5.7 (JP) can not work properly

**Comment by DonKalypso** [comment]
I, too, am having a problem similar to the one ragingchaos is having.
https://www.dropbox.com/s/63lte3pt1stsolm/Screenshot%202017-03-06%2022.50.18.png?dl=0
The above happens in the command window when I launch FFRK.
https://www.dropbox.com/s/96cu1z1oifuluyl/Screenshot%202017-03-06%2022.51.37.png?dl=0
And that is what my settings look like in KOPlayer.

To get the command window to do what it does I made the whitelist setting in default.yml set to false. The IP it's trying to connect to is my Hamachi IP, if that changes anything. Due to circumstances I'm not able to set my router to port forward.

**Comment by ThauEx** [comment]
I can't tell you why, but for some reason it tries to connect to `127.0.0.1`, which is not possible.
The is the loopback address of your phone, so it is basicly targeting your phone, but when the proxy tries to resolve this, it is pointing to the proxy. This is because `127.0.0.1` is always the device itself.

**Comment by DonKalypso** [comment]
I've managed to solve the issue by swapping to another emulator. Fortunately the progress is connected to my Google account. In the new emulator I'm using the built in proxy thing, but now I occasionally get a "We're not able to connect" message, but the game keeps operating.

Also currently chunking through the .yml file to make it so my team isn't super OP.
