### ISSUE TITLE
Break Damage Limit

### ISSUE THREAD

**Issue by Cissamannen** [ThauEx/ffrk-proxy#82]
So, in the light lf this new ultra soul break of Cloud, is it possible to add this soldier buff permanently on start of battle? It lets the player do 99999 damage on all types of attacks.

**Comment by ThauEx** [comment]
Can't tell you, I'm not playing this game anymore and I think they have some extra logic for SBs to change the damage there.

**Comment by SimonOmega** [comment]
Add this to ailments.json right below REGEN_STRONG (id 243) right after the ` },`.
All three work, but you want "BUSTER_SWORD_MODE".
`  "GUTS_1": {
    "id": 261,
    "description": "Last Stand"
  },
  "STATUS_AILMENTS_BARRIER": {
    "id": 271,
    "description": "ASTRA"
  },
  "BUSTER_SWORD_MODE": {
    "id": 276,
    "description": "EX: Soldier"
  },`

**Comment by jdel** [comment]
Thanks for this, I have tested successfully and made a PR.

**Comment by SimonOmega** [comment]
@jdel Thank You.  I only had time to post it after I found it. I fell asleep.

**Comment by Cissamannen** [comment]
Amazing work! Though I do not know what Last Stand or Astra does x)

**Comment by SimonOmega** [comment]
Last Stand (Code: GUTS_1) when a hit would KO you, the damage taken stops so that you have 1% health remaining.  This does not count as a resurrection and gives you one last chance.

Astra (Code: STATUS_AILMENTS_BARRIER) blocks the next debuff that would apply to the character.  Most debuffs are supported.  e.g. If you get hit with poison, and you have no poison resist gear on, this will cancel the poison.

**Comment by Cissamannen** [comment]
Ive tried adding the EX soldier mode, but doesnt grant me any. Still doing 9999 damage per hit :/

**Comment by SimonOmega** [comment]
@Cissamannen that is odd as it worked for @jdel and myself.  I will admit I added mine in the defaults section of config.js.  I know very little NodeJS and even less YAML. @ThauEx had to convince me to go the NodeJS route because of this.  I was still using MiTM Proxy.

In your yml config did you use a sequence ( - at the begining of each line ) or did you use a bracketed sequence ( comma separated list  inside of [ ] the or { } ).  My terminology may be off.  

I can experiment with it once I get home, but I know you can add it directly as a default.

**Comment by Cissamannen** [comment]
Yeah I have gotten it to work :) Not sure you got the edited message xD

**Comment by SimonOmega** [comment]
No Problems :-) Glad it works.
