### ISSUE TITLE
Stacking multiple RM or changing it

### ISSUE THREAD

**Issue by taufieq89** [ThauEx/ffrk-proxy#93]
Hello. Million thanks first to @ThauEx  and @KHShadowrunner for making this proxy possible.

On to the question, is it possible for me to stack multiple RMs which in my case are Bard's Zealot and Luneth's Fast Learner on buddies. If it's impossible, how can I replace it with Luneth's?

**Comment by ThauEx** [comment]
Hi,
as far as I can tell from the code, you can only have one at the time.
See here for the Zealot implementation:
https://github.com/ThauEx/ffrk-proxy/blob/master/lib/filter/buddy.js#L121-L127

**Comment by taufieq89** [comment]
Thank you so much for the fast reply. So, from my understanding I need to have the data on Luneth's RM in the recordmateria.json then replace it within buddy.js is it? I'm a complete noob in this so it will be so much help if you could guide me in the right direction.

**Comment by ThauEx** [comment]
Currently it's a little bit complicated, because configurable RMs are not implemented.
Yes, the first step would be to add it in `recordmateria.json`.
Next step step is to add it in `buddy.js`, we could make both available (via config).
Just copy the current block and add another for the new RM and maybe add a check so only one of them can be used. You also have to add it in `config.js`, to make it configurable.

BTW: What is `Luneth's Fast` exacly doing?

**Comment by taufieq89** [comment]
Generating a code is really out of my league though XD

*Its similar to Cid's Ace Pilot but with 40% chance compared to 20% to gain double EXP

**Comment by ThauEx** [comment]
Well, generating the code is quite easy I think... It shoud be in your dumps (afair)

**Comment by taufieq89** [comment]
So I need to check the dump and check for when the materia proc and start from there?

**Comment by ThauEx** [comment]
Yeah, it's somewhere there. Then you have to copy the code to the json and after that modify `buddy.json`
