### ISSUE TITLE
Does this work with iOS 10/11? 

### ISSUE THREAD

**Issue by seanbperiod** [ThauEx/ffrk-proxy#97]
I know there's an issue with other hosted proxy servers (ffrkproxy, sphinxara) on iOS 10 and 11, but iOS 9 and below continue to work. Will this home spun proxy server work for current versions of iOS?

**Comment by ThauEx** [comment]
Hi,
I don't have any iOS devices and I'm not playing the game anymore, so I cannot help you 😕.
Maybe someone else can help you.

**Comment by seanbperiod** [comment]
Thanks for the quick response! 

Hopefully someone else will know.

**Comment by sephysama** [comment]
I just saw this comment and figured I could help.  When I originally ran the proxy server, it worked fine.  Then when I upgraded to a newer version (anything > 5.0.0) it stopped working.  Since I'm jailbroken, I could use appcake to download an older version of the app and the proxy started working again.  I'm gonna check appcake to see if it still has 5.0.0.  If it does, I'll try updating the app again and seeing if the proxy works or not.  When on the newer version of ffrk, for some reason I would always get some kind of error status connecting to the ffrk servers.

**Comment by seanbperiod** [comment]
@sephysama I believe it has little  to do with the version number of the game, but more the iOS version. I think anything below iOS 10 will work fine, as I have a jailbroken iPad on 9.0.2 with the latest version of the game and it continues to work fine with the proxy. I read that the game uses some kind of SSL in the latest versions of iOS which prevents the proxy server from working.

**Comment by sephysama** [comment]
I'm running iOS 10 and it works fine on FFRK v 5.0.0 .  Anything newer than that and it craps out.  I think the newer versions are maybe generating some kind of security certificate that the proxy can't verify?

**Comment by seanbperiod** [comment]
@sephysama oh I didn't know that. That's good news - I thought older versions would have a message forcing you to upgrade. I just checked appcake and only see dead links for 4.0.6 and below. Any chance you would package and share your version?

**Comment by sephysama** [comment]
are you on 32-bit or 64-bit iPad?  I think the reason it's not showing up for you is compatibility.  My appcake ONLY shows 5.0.0, so I'm guessing it might be a compatibility thing.

**Comment by seanbperiod** [comment]
@sephysama Mini 2 - A7 - 64bit I was checking on the AppCake 4 because it has a better archive than the new Appcake.

**Comment by sephysama** [comment]
Ah, okay! I'm running Appcake 5.5.5.0.  That one shows FFRK v 5.0.0 for me.  Maybe try that?

**Comment by seanbperiod** [comment]
Yep. that only shows 5.0. If you use AppCake 4 legacy, you get a better updated archive and it mirrors iphonecake.com. So just to confirm the FFRK 5.0 on AppCake 5 works on iOS 10? (i'm hoping it will work on  iOS11 when that JB comes out)

**Comment by sephysama** [comment]
i'm running an iPhone 6+, FFRK 5.0.0 with iOS 10.2 yalu102 JB and it works absoluetly fine.  Just don't update past 5.0.0, that's when you get the TSL certificate error.  All the game updates seem to go through, i don't THINK i'm missing anything.  I hope not anyways.

**Comment by sephysama** [comment]
Hope everything worked out for you!

**Comment by dwoo415** [comment]
I believe its the app version. The last version that worked for me on iOS is 5.1.2. I accidentally deleted my app so I used Charlie and an old version of iTunes to download the old version of the app. From the logs on ffrk-proxy, it appears that newer versions of the app is using HTTPS instead of HTTP to make the calls to the FFRK servers, which is giving ffrk-proxy issues. This does not happen on the Android version.

**Comment by ThauEx** [comment]
All versions of ffrk are using https. They only added some new layer of security, so the battle data is not readable that easy.

**Comment by Dorzalty** [comment]
Is there any chance to get around this issue for iOS? This game is a nightmare without this proxy and the only other apparent proxy charges obscene amounts of money to be able to use it every day. Besides jailbreaking and probably going back to an early iOS version, is there anything we can do?

**Comment by ThauEx** [comment]
I will try to prepare a pre release this weekend.

**Comment by Dorzalty** [comment]
Thank you ThauEx, we appreciate all your hard work! Your proxy has made this game a little fairer to the F2P community and overall way less of an annoying grind for huge events for just about everyone. :+1:

**Comment by ThauEx** [comment]
See here: https://github.com/ThauEx/ffrk-proxy/issues/106#issuecomment-368334741
